KEY_TEST_68

diff --git a/.github/workflows/chat_gpt2.yaml b/.github/workflows/chat_gpt2.yaml
--- a/.github/workflows/chat_gpt2.yaml
+++ b/.github/workflows/chat_gpt2.yaml
@@ -64,10 +64,11 @@ jobs:
 
     - name: Check Build Output
       run: |
-        BUILD_PATH=$(npm run build --silent | grep 'The files will be written to' | cut -d':' -f2)
+        npm run build
+        BUILD_PATH="./build"  # 수정 필요
         if [ -z "$BUILD_PATH" ]; then
-        echo "Error: Build path not found."
-        exit 1
+          echo "Error: Build path not found."
+          exit 1
         fi
         echo "Build Path: $BUILD_PATH"
         ls -la "$BUILD_PATH"
